package ro.upb.mitmdetector;

import org.junit.jupiter.api.Test;
import ro.upb.mitmdetector.alert.Alert;
import ro.upb.mitmdetector.alert.AlertManager;
import ro.upb.mitmdetector.alert.AlertType;
import ro.upb.mitmdetector.alert.Severity;
import ro.upb.mitmdetector.capture.PacketCaptureEngine;
import ro.upb.mitmdetector.detector.ArpDetector;

import java.net.URISyntaxException;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * End-to-end check: a saved capture goes through the real capture engine and the real ArpDetector.
 *
 * <p>Needs Npcap (Windows) or libpcap (Linux/macOS) installed, because Pcap4J reads the file
 * through the native library. The captures are generated by tools/make_sample_pcaps.py.
 */
class PcapReplayTest {

    private static final String ATTACKER_MAC = "cc:cc:cc:cc:cc:66";
    private static final String GATEWAY_IP = "192.168.1.1";

    private static AlertManager replay(String resource) throws Exception {
        AlertManager alerts = new AlertManager();
        try (PacketCaptureEngine engine = PacketCaptureEngine.forFile(pathOf(resource))) {
            engine.addDetector(new ArpDetector(alerts));
            engine.start();
            engine.awaitCompletion();
            assertTrue(engine.packetCount() > 0, "no packets were read from " + resource);
        }
        return alerts;
    }

    private static String pathOf(String resource) throws URISyntaxException {
        var url = PcapReplayTest.class.getResource(resource);
        if (url == null) {
            throw new IllegalStateException("Missing test resource " + resource
                    + " (run python tools/make_sample_pcaps.py)");
        }
        return Path.of(url.toURI()).toString();
    }

    @Test
    void normalTrafficProducesNoAlerts() throws Exception {
        AlertManager alerts = replay("/pcap/normal_arp.pcap");
        assertTrue(alerts.history().isEmpty(), "unexpected alerts: " + alerts.history());
    }

    @Test
    void poisoningIsDetected() throws Exception {
        AlertManager alerts = replay("/pcap/arp_spoofing.pcap");

        List<Alert> spoofing = alerts.history().stream()
                .filter(a -> a.type() == AlertType.ARP_SPOOFING).toList();
        assertEquals(1, spoofing.size(), "history: " + alerts.history());
        assertEquals(Severity.CRITICAL, spoofing.get(0).severity());
        assertEquals(GATEWAY_IP, spoofing.get(0).sourceIp());
        assertEquals(ATTACKER_MAC, spoofing.get(0).sourceMac());

        long floods = alerts.history().stream()
                .filter(a -> a.type() == AlertType.ARP_UNSOLICITED_FLOOD).count();
        assertEquals(1, floods, "history: " + alerts.history());
    }
}
