package ro.upb.mitmdetector;

import org.junit.jupiter.api.Test;
import ro.upb.mitmdetector.alert.Alert;
import ro.upb.mitmdetector.alert.AlertManager;
import ro.upb.mitmdetector.alert.AlertType;
import ro.upb.mitmdetector.alert.Severity;
import ro.upb.mitmdetector.capture.PacketCaptureEngine;
import ro.upb.mitmdetector.detector.ArpDetector;
import ro.upb.mitmdetector.detector.DhcpDetector;
import ro.upb.mitmdetector.detector.DnsDetector;

import java.net.URISyntaxException;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * End-to-end check: a saved capture goes through the real capture engine and the real ArpDetector.
 *
 * <p>Needs Npcap (Windows) or libpcap (Linux/macOS) installed, because Pcap4J reads the file
 * through the native library. The captures are generated by tools/make_sample_pcaps.py.
 */
class PcapReplayTest {

    private static final String ATTACKER_MAC = "cc:cc:cc:cc:cc:66";
    private static final String GATEWAY_IP = "192.168.1.1";
    private static final String ATTACKER_IP = "192.168.1.66";

    private static AlertManager replay(String resource) throws Exception {
        AlertManager alerts = new AlertManager();
        try (PacketCaptureEngine engine = PacketCaptureEngine.forFile(pathOf(resource))) {
            engine.addDetector(new ArpDetector(alerts));
            engine.addDetector(new DnsDetector(alerts));
            engine.addDetector(new DhcpDetector(alerts));
            engine.start();
            engine.awaitCompletion();
            assertTrue(engine.packetCount() > 0, "no packets were read from " + resource);
        }
        return alerts;
    }

    private static String pathOf(String resource) throws URISyntaxException {
        var url = PcapReplayTest.class.getResource(resource);
        if (url == null) {
            throw new IllegalStateException("Missing test resource " + resource
                    + " (run python tools/make_sample_pcaps.py)");
        }
        return Path.of(url.toURI()).toString();
    }

    @Test
    void normalTrafficProducesNoAlerts() throws Exception {
        AlertManager alerts = replay("/pcap/normal_arp.pcap");
        assertTrue(alerts.history().isEmpty(), "unexpected alerts: " + alerts.history());
    }

    @Test
    void poisoningIsDetected() throws Exception {
        AlertManager alerts = replay("/pcap/arp_spoofing.pcap");

        List<Alert> spoofing = alerts.history().stream()
                .filter(a -> a.type() == AlertType.ARP_SPOOFING).toList();
        assertEquals(1, spoofing.size(), "history: " + alerts.history());
        assertEquals(Severity.CRITICAL, spoofing.get(0).severity());
        assertEquals(GATEWAY_IP, spoofing.get(0).sourceIp());
        assertEquals(ATTACKER_MAC, spoofing.get(0).sourceMac());

        long floods = alerts.history().stream()
                .filter(a -> a.type() == AlertType.ARP_UNSOLICITED_FLOOD).count();
        assertEquals(1, floods, "history: " + alerts.history());
    }

    @Test
    void normalDnsTrafficProducesNoAlerts() throws Exception {
        AlertManager alerts = replay("/pcap/normal_dns.pcap");
        assertTrue(alerts.history().isEmpty(), "unexpected alerts: " + alerts.history());
    }

    @Test
    void dnsSpoofingIsDetected() throws Exception {
        AlertManager alerts = replay("/pcap/dns_spoofing.pcap");
        assertEquals(3, alerts.history().size(), "history: " + alerts.history());

        Alert changed = only(alerts, AlertType.DNS_ANSWER_CHANGED);
        assertEquals(Severity.HIGH, changed.severity());
        assertEquals(GATEWAY_IP, changed.sourceIp());
        assertEquals(ATTACKER_MAC, changed.sourceMac());

        Alert conflict = only(alerts, AlertType.DNS_CONFLICTING_RESPONSES);
        assertEquals(Severity.CRITICAL, conflict.severity());
        assertEquals(ATTACKER_MAC, conflict.sourceMac());

        Alert unsolicited = only(alerts, AlertType.DNS_UNSOLICITED_RESPONSE);
        assertEquals(Severity.MEDIUM, unsolicited.severity());
        assertEquals(ATTACKER_MAC, unsolicited.sourceMac());
    }

    @Test
    void normalDhcpTrafficProducesNoAlerts() throws Exception {
        AlertManager alerts = replay("/pcap/normal_dhcp.pcap");
        assertTrue(alerts.history().isEmpty(), "unexpected alerts: " + alerts.history());
    }

    @Test
    void rogueDhcpServerIsDetected() throws Exception {
        AlertManager alerts = replay("/pcap/dhcp_rogue.pcap");
        assertEquals(3, alerts.history().size(), "history: " + alerts.history());

        Alert conflict = only(alerts, AlertType.DHCP_CONFLICTING_OFFERS);
        assertEquals(Severity.CRITICAL, conflict.severity());
        assertEquals(ATTACKER_IP, conflict.sourceIp());
        assertEquals(ATTACKER_MAC, conflict.sourceMac());

        List<Alert> rogue = alerts.history().stream()
                .filter(a -> a.type() == AlertType.DHCP_ROGUE_SERVER).toList();
        assertEquals(2, rogue.size(), "history: " + alerts.history());
        assertEquals(Severity.HIGH, rogue.get(0).severity());          // the second server
        assertEquals(ATTACKER_IP, rogue.get(0).sourceIp());
        assertEquals(Severity.CRITICAL, rogue.get(1).severity());      // the real server's IP from another MAC
        assertEquals(GATEWAY_IP, rogue.get(1).sourceIp());
        assertEquals(ATTACKER_MAC, rogue.get(1).sourceMac());
    }

    private static Alert only(AlertManager alerts, AlertType type) {
        List<Alert> matching = alerts.history().stream().filter(a -> a.type() == type).toList();
        assertEquals(1, matching.size(), type + " in " + alerts.history());
        return matching.get(0);
    }
}
